# yaml configration of hyperparameters

# random seeds
seed: 1999

# mode: "train", "test"
mode: 'train'
# do we have checkpoint in current stage
checkpoint: false


# dataset: voc,..., see more details in main.py 'models_implemented'
dataset: 'voc'
# if you have already downloaded this dataset, make it to false
need_download: false

# task (see more details in ./datasets/task.py)
#  voc: offline, 19-1, 19-1b, 15-5, 15-5s, 10-5-5...
task: '19-1'
# stage (see more details in ./datasets/task.py)
stage: 0

### 常用参数
# make part of train set to be validation set
partition: true
# partition ratio
partition_r: 0.8
# batch size of one iter
batch_size: 4
# num of workers
num_workers: 4
# backbone (see more details in dir ./models)
backbone: 'deeplabv3_resnet101'
# epochs
epochs: 30
# learning rate of model
lr: 0.01
# learning rate policy ‘cos', 'step', 'poly'
lr_policy: 'poly'
# learning rate decreasing power of lr_policy='poly'
lr_power: 0.9
# weight decay
weight_decay: 0.0001
# resize the input picture and mask to cropped_size
cropped_size: 512
# classifier name
classifier_name: 'classifier.4'
# scale of local pod
scale: 2
# alpha of distillation loss
alpha: 1.0
# classifier init method 'kaiming', 'xavier', 'mib', 'rand_new'
classifier_init_method: 'mib'
###

# path of dataset
path_dataset: './data/'
# path of states
path_state: './states/plop'
# path of tensorboard
path_tb: './log/tb'
