# yaml
# dataset: voc,..., see more details in main.py 'models_implemented'
dataset: 'voc'

# if you have already downloaded this dataset, make it to false
need_download: false

# random seeds
seed: 1999

# task (see more details in ./datasets/task.py)
#  voc: offline, 19-1, 19-1b, 15-5, 15-5s, 10-5-5
#  ...
task: '15-5'

# stage (see more details in ./datasets/task.py)
stage: 0

# path of dataset
path_dataset: './data/'

# make part of train set to be validation set
partition: true
# partition ratio
partition_r: 0.8

# batch size of one iter
batch_size: 3

# num of workers
num_workers: 4

# backbone (see more details in dir ./models)
backbone: 'deeplabv3_resnet50'

# epochs
epochs: 30

# learning rate of model
lr: 0.002

# learning rate policy ‘cos', 'step'
lr_policy: 'cos'

# do we have checkpoint in current stage
checkpoint: false

# loss 'MiB', 'CE'
loss: 'MiB'

# weight decay
weight_decay: 0.0001

# resize the input picture size
cropped_size: 512